### ISSUE TITLE
Discord request headers

### ISSUE THREAD

**Issue by Aniell4** [pinkcig/puro#1]
1. cookies should be randomized, discord will flag them after a while if they are static.
2. more headers should be added, these headers will most likely flag unclaimed accounts see [this](https://github.com/Aniell4/Discord-Friend-Request-Spammer/blob/main/main.py) for more complete headers ( ofc "x-context-properties" is an exception ).

Other than that, great project ! I like the idea and I can see this coming along nicely 😁

**Comment by pinkcig** [comment]
Thanks for the head up, I'll modify it ASAP

**Comment by pinkcig** [comment]
ffeccdb addresses this
